services:
  evcc-webui:
    build: .
    container_name: evcc-webui
    restart: unless-stopped
    ports:
      - "5080:5080"
    environment:
      # Point this to your EVCC API
      EVCC_BASE_URL: "http://172.16.1.179:7070/api"
      # Default loadpoint shown/controlled on first load
      DEFAULT_LP_ID: "1"
      # Your 120s anti-flap window
      MODE_COOLDOWN_SECONDS: "120"
      # Optional: you can add FLASK_HOST/FLASK_PORT, but gunicorn already binds 0.0.0.0:5080
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:5080/status >/dev/null || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s
